### ISSUE TITLE
Compile error in alpine

### ISSUE THREAD

**Issue by JoeOrtiz** [mailru/graphite-nginx-module#1]
When attempting to compile on alpine with nginx 1.8.0 I get the following

```
        ../graphite-nginx-module/src/ngx_http_graphite_module.c
../graphite-nginx-module/src/ngx_http_graphite_module.c: In function 'ngx_http_graphite_timer_event_handler':
../graphite-nginx-module/src/ngx_http_graphite_module.c:1239:56: error: passing argument 5 of 'sendto' from incompatible pointer type [-Werror]
                 if (sendto(fd, part, nl - part + 1, 0, &sin, sizeof(sin)) == -1)
                                                        ^
In file included from src/os/unix/ngx_linux_config.h:44:0,
                 from src/core/ngx_config.h:26,
                 from ../graphite-nginx-module/src/ngx_http_graphite_module.c:1:
/usr/include/fortify/sys/socket.h:53:9: note: expected 'const struct sockaddr *' but argument is of type 'struct sockaddr_in *'
 ssize_t sendto(int sockfd, const void *buf, size_t n, int flags,
         ^
cc1: all warnings being treated as errors
objs/Makefile:1446: recipe for target 'objs/addon/src/ngx_http_graphite_module.o' failed
make[1]: *** [objs/addon/src/ngx_http_graphite_module.o] Error 1
make[1]: Leaving directory '/nginx-1.8.0'
Makefile:8: recipe for target 'build' failed
make: *** [build] Error 2
```

Any ideas what would be causing it?

**Comment by JoeOrtiz** [comment]
If I change this line:

https://github.com/mailru/graphite-nginx-module/blob/master/src/ngx_http_graphite_module.c#L1239

To:

```
if (sendto(fd, part, nl - part + 1, 0, (struct sockaddr *)&sin, sizeof(sin)) == -1)
```

It works...think this would affect anything?

**Comment by kirimedia** [comment]
Yes it works. We will soon merge the change to the master branch.
