### ISSUE TITLE
Couldn't build with nginx 1.13.12

### ISSUE THREAD

**Issue by cryptofuture** [mailru/graphite-nginx-module#20]
```
	-o objs/addon/src/ngx_http_graphite_module.o \
	debian/extra/graphite-nginx-module/src/ngx_http_graphite_module.c
debian/extra/graphite-nginx-module/src/ngx_http_graphite_module.c: In function 'ngx_http_graphite_source_content_time':
debian/extra/graphite-nginx-module/src/ngx_http_graphite_module.c:2785:21: error: 'ngx_http_request_t {aka struct ngx_http_request_s}' has no member named 'content_time'
     return (double)r->content_time;
                     ^
debian/extra/graphite-nginx-module/src/ngx_http_graphite_module.c: In function 'ngx_http_graphite_source_gzip_time':
debian/extra/graphite-nginx-module/src/ngx_http_graphite_module.c:2791:21: error: 'ngx_http_request_t {aka struct ngx_http_request_s}' has no member named 'gzip_time'
     return (double)r->gzip_time;
                     ^
debian/extra/graphite-nginx-module/src/ngx_http_graphite_module.c: In function 'ngx_http_graphite_source_lua_time':
debian/extra/graphite-nginx-module/src/ngx_http_graphite_module.c:2877:13: error: 'ngx_http_request_t {aka struct ngx_http_request_s}' has no member named 'lua_time'
     return r->lua_time;
             ^
debian/extra/graphite-nginx-module/src/ngx_http_graphite_module.c:2878:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
debian/extra/graphite-nginx-module/src/ngx_http_graphite_module.c: In function 'ngx_http_graphite_source_gzip_time':
debian/extra/graphite-nginx-module/src/ngx_http_graphite_module.c:2792:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
debian/extra/graphite-nginx-module/src/ngx_http_graphite_module.c: In function 'ngx_http_graphite_source_content_time':
debian/extra/graphite-nginx-module/src/ngx_http_graphite_module.c:2786:1: error: control reaches end of non-void function [-Werror=return-type]
 }
 ^
cc1: all warnings being treated as errors
objs/Makefile:3843: recipe for target 'objs/addon/src/ngx_http_graphite_module.o' failed

```

**Comment by kirimedia** [comment]
You need use graphite module patch for nginx.
Please see https://github.com/mailru/graphite-nginx-module#installation

**Comment by cryptofuture** [comment]
Its patched. Build would stop if Hunk fails.

**Comment by kirimedia** [comment]
The patch should work.
What versions of the module and patch do you use?
Do you have any other patches applied?

```
[root@hive6 develop]# wget http://nginx.org/download/nginx-1.13.12.tar.gz
--2018-05-24 17:29:15--  http://nginx.org/download/nginx-1.13.12.tar.gz
Resolving nginx.org (nginx.org)... 95.211.80.227, 206.251.255.63, 2606:7100:1:69::3f, ...
Connecting to nginx.org (nginx.org)|95.211.80.227|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1016311 (992K) [application/octet-stream]
Saving to: ‘nginx-1.13.12.tar.gz’

100%[=====================================================================================================================================================================================================================================>] 1,016,311   2.21MB/s   in 0.4s   

2018-05-24 17:29:16 (2.21 MB/s) - ‘nginx-1.13.12.tar.gz’ saved [1016311/1016311]

[root@hive6 develop]# tar -xzf nginx-1.13.12.tar.gz 
[root@hive6 develop]# cd nginx-1.13.12
[root@hive6 nginx-1.13.12]# patch -p1 < ../graphite-nginx-module/graphite_module_v1_7_7.patch 
patching file src/event/ngx_event_openssl.c
Hunk #1 succeeded at 1229 (offset 1 line).
Hunk #2 succeeded at 1318 (offset 1 line).
patching file src/event/ngx_event_openssl.h
Hunk #1 succeeded at 80 (offset 1 line).
patching file src/http/modules/ngx_http_gzip_filter_module.c
Hunk #1 succeeded at 427 (offset 3 lines).
patching file src/http/ngx_http_core_module.c
Hunk #1 succeeded at 1166 (offset -218 lines).
patching file src/http/ngx_http_request.h
Hunk #1 succeeded at 585 (offset 5 lines).
```

**Comment by cryptofuture** [comment]
You could check it [there](https://github.com/cryptofuture/nginx-hda-bundle), but I didn't uploaded changes for nginx 1.13.12 (as I now temporarily disabled graphite), but actually you could just drop 1.13.12 source. All patches are located under `/debian/patches/`
If any hunk had failed, it would just didn't even start building.

**Comment by kirimedia** [comment]
We are writing patchs for the original sources of nginx. 
You have problems with the interaction of patches of different modules.
You can not use the patch of graphite and lua modules or apply the graphite module patches first.
