### ISSUE TITLE
Fails to compile with ubuntu 12.04

### ISSUE THREAD

**Issue by gbjtv** [mailru/graphite-nginx-module#4]
cc -c -pipe  -O -W -Wall -Wpointer-arith -Wno-unused-parameter -Werror -g   -I src/core -I src/event -I src/event/modules -I src/os/unix -I objs -I src/http -I src/http/modules -I src/mail \
        -o objs/addon/src/ngx_http_graphite_module.o \
        ../graphite-nginx-module/src/ngx_http_graphite_module.c
../graphite-nginx-module/src/ngx_http_graphite_module.c: In function 'ngx_http_graphite_param_ssl_handshake_time':
../graphite-nginx-module/src/ngx_http_graphite_module.c:1402:39: error: 'ngx_ssl_connection_t' has no member named 'handshake_end_sec'
../graphite-nginx-module/src/ngx_http_graphite_module.c:1402:64: error: 'ngx_ssl_connection_t' has no member named 'handshake_start_sec'
../graphite-nginx-module/src/ngx_http_graphite_module.c:1402:100: error: 'ngx_ssl_connection_t' has no member named 'handshake_end_msec'
../graphite-nginx-module/src/ngx_http_graphite_module.c:1402:126: error: 'ngx_ssl_connection_t' has no member named 'handshake_start_msec'
../graphite-nginx-module/src/ngx_http_graphite_module.c: In function 'ngx_http_graphite_param_content_time':
../graphite-nginx-module/src/ngx_http_graphite_module.c:1450:29: error: 'ngx_http_request_t' has no member named 'content_end_sec'
../graphite-nginx-module/src/ngx_http_graphite_module.c:1450:50: error: 'ngx_http_request_t' has no member named 'content_start_sec'
../graphite-nginx-module/src/ngx_http_graphite_module.c:1450:82: error: 'ngx_http_request_t' has no member named 'content_end_msec'
../graphite-nginx-module/src/ngx_http_graphite_module.c:1450:104: error: 'ngx_http_request_t' has no member named 'content_start_msec'
../graphite-nginx-module/src/ngx_http_graphite_module.c: In function 'ngx_http_graphite_param_gzip_time':
../graphite-nginx-module/src/ngx_http_graphite_module.c:1464:29: error: 'ngx_http_request_t' has no member named 'gzip_end_sec'
../graphite-nginx-module/src/ngx_http_graphite_module.c:1464:47: error: 'ngx_http_request_t' has no member named 'gzip_start_sec'
../graphite-nginx-module/src/ngx_http_graphite_module.c:1464:76: error: 'ngx_http_request_t' has no member named 'gzip_end_msec'
../graphite-nginx-module/src/ngx_http_graphite_module.c:1464:95: error: 'ngx_http_request_t' has no member named 'gzip_start_msec'
make[1]: **\* [objs/addon/src/ngx_http_graphite_module.o] Error 1
make[1]: **\* Waiting for unfinished jobs....
make[1]: Leaving directory `/tmp/nginx/nginx-1.8.0'
make: **\* [build] Error 2

**Comment by gbjtv** [comment]
missed the patch . ignore me.

**Comment by kirimedia** [comment]
Do you apply the patch to nginx before build?

```
patch -p1 < /path/to/graphite-nginx-module/graphite_module_v1_7_7.patch
```

**Comment by brisssou** [comment]
The patch is indicated as optional in the install documentation.

I would have expect the module to compile without this patch. Now I am sad.

**Comment by brisssou** [comment]
hey, thanks a lot! I did not expect to issue to get re-opened.

**Comment by kirimedia** [comment]
I'll fix it soon.

**Comment by kirimedia** [comment]
I fixed it
